title: "ç¥¥å®‰ç”Ÿå‘½æœ‰é™å…¬å¸"
email: ava85110@yahoo.com.tw
description: "æä¾›å¾€ç”Ÿæ¥é«”ã€å–ªè‘¬è£œåŠ©ã€ç¿’ä¿—æµç¨‹ç­‰ç”Ÿå‘½æœå‹™å°ˆæ¥­çŸ¥è­˜ã€‚"
baseurl: "/Shiangan" # ğŸ’¡ æ ¹æ“šæ‚¨çš„ GitHub Pages URL èª¿æ•´
url: "https://24hour.xn--kpry57d" 
# --------------------
# Jekyll é…ç½®
# --------------------
permalink: /:title.html 
paginate: 10 
paginate_path: "/blog/page:num/"
timezone: Asia/Taipei
# --------------------
plugins:
  - jekyll-paginate
# --------------------
